version: '3.7'
services:
  database:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root	
    - MYSQL_DATABASE=flask-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
  flask-app-1:
    image: service1?

  flask-app-2:
    image: service2?
 
  flask-app-3:
    image: service3
    deploy: 
      replicas: 2
  flask-app-4:
    image: service4
    ports: 
    - target: 5000
      published: 5000
    deploy:
      replicas: 4

volumes:
  db-data: